# Generated by Django 5.0.3 on 2024-03-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('idade', models.PositiveIntegerField(default=12)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
